package com.hp.qiushibaike;

import android.text.TextUtils;

public class Constants
{
  public static String APPINFO;
  public static final String APP_ID = "wxfa4ebf0331513c10";
  public static String APP_LOGS;
  public static String ARATAR_URL;
  public static String ARTICLE_CREATE;
  public static String AUDIT;
  public static String BINDEMAIL;
  public static final String CAFE_UPGRADE_URL = "http://cafe.qiushibaike.com/cafe/new_version";
  public static final String CHAT_BLACK_LIST = "http://msg.qiushibaike.com/messages/buddy/%s/blacklist?src=android";
  public static final String CHAT_DELETE = "http://msg.qiushibaike.com/messages/conv/%s?src=android";
  public static final String CHAT_REPORT = "http://msg.qiushibaike.com/messages/buddy/%s/report?src=android";
  public static final String CHAT_SERVER = "http://msg.qiushibaike.com/messages";
  public static final String CHAT_UNREAD = "http://msg.qiushibaike.com/messages/unread?src=android";
  public static String COLLECT;
  public static String COLLECT_LIST;
  public static String COMMENT;
  public static String COMMENT_CREATE;
  public static String CONFIG;
  public static final String CONTENT_CACHE_PATH = "/content";
  public static String CONTENT_DOMAINS;
  public static String CONTENT_IMAGE_URL;
  public static final int CommentCount = 50;
  public static String DAY;
  public static String DELETE_COLLECT;
  public static String DELETE_CREATE;
  public static String FEEDBACK;
  public static String FILLINFO;
  public static String HISTORY;
  public static String HOT_IMAGES;
  public static String IMAGES;
  public static final String IMG_CACHE_PATH_AVATAR = "/avatar";
  public static final String IMG_CACHE_PATH_MEDIUM = "/medium";
  public static final String IMG_CACHE_PATH_PRE = "/pre";
  public static String IMG_DOMAINS;
  public static final String IMG_DOMAIN_BACKUP = "http://img0.qiushibaike.com/";
  public static String INSP;
  public static String IS_UNSUBSCRIBE_TA;
  public static String LATEST;
  public static String LIKE;
  public static String LOGIN;
  public static String MAINPAGE;
  public static String MAINPAGE_ACTORS;
  public static String MAINPAGE_CHECK;
  public static String MONTH;
  public static String MYCONTENTS;
  public static String MY_INFO;
  public static String NEARBY;
  public static String NOTIFY_SETTING_GET;
  public static String NOTIFY_SETTING_SET;
  public static String OFFICIAL;
  public static String OFFICIAL_INFO;
  public static String OFFICIAL_SUBSCRIBE;
  public static String OFFICIAL_SUBSCRIBE_LIST;
  public static String ONES_ARTICLES;
  public static String PARTICIPATE;
  public static String PUSH_DOMAINS;
  public static String PUSH_DOMAINS_TEST;
  public static String REGISTER;
  public static String RELATIONSHIP;
  public static String REL_BLACK;
  public static String REL_DELETE_NEW_FANS = RELATIONSHIP + "/relationship/%s/update_new_fan_list";
  public static String REL_FOLLOW;
  public static String REL_GET_BLACKLIST;
  public static String REL_GET_FANS;
  public static String REL_GET_FOLLOWS;
  public static String REL_GET_FRIENDS;
  public static String REL_GET_RELATIONSHIP;
  public static String REL_MOVEOFF_BLACKLIST;
  public static String REL_NEW_FAN_COUNT;
  public static String REL_NEW_FAN_LIST;
  public static String REL_UNFOLLOW;
  public static String REPORT;
  public static String REPORT_ARTICLE;
  public static String REPORT_COMMENT;
  public static final String SHARE_URL = "http://share.qiushibaike.com/article/%1$s/share";
  public static String SUBSCRIBE_TA;
  public static String SUGGEST;
  public static final String TEST_SERVER = "http://119.29.8.233:10200/";
  public static String TEXT;
  public static String THIRDPARTY_LOGIN;
  public static String TOPIC_CLICK_STATISTIC;
  public static String UNBIND_THIRD_PARTY;
  public static String UNSUBSCRIBE_TA;
  public static String UPDATE_AVATAR;
  public static final long UPDATE_INTERVAL = 86400000L;
  public static String UPDATE_URL;
  public static String UPDATE_USERINFO;
  public static String URL_CLEAR;
  public static String URL_CONFIG;
  public static String URL_FETCH;
  public static String URL_GET_TOKEN;
  public static final String URL_GET_TOKEN_FOR_GROUP = "http://119.29.8.233:10200/tribe/pic/uptoken";
  public static final String URL_GROUP_DETAIL = "http://119.29.8.233:10200/tribe/%s/detail?tid=%d";
  public static final String URL_IMAGE_KEY_FOR_GROUP = "http://119.29.8.233:10200/tribe/pic";
  public static String URL_MOBILE_BRAND_LIST;
  public static String URL_QINIU_KEY;
  public static String URL_RANDOM_DOOR_UPDATE;
  public static String URL_SEARCH_QIUYOU;
  public static String URL_USER_INFO;
  public static String USERINFO;
  public static String USER_AVAILABLE;
  public static final String USER_EVALUATE = "http://api.qiushibaike.com/eval";
  public static String VERIFY;
  public static String VERIFY_EMAIL;
  public static final long VERIFY_INTERVAL = 259200000L;
  public static String VIDEO;
  public static String VIDEO_LOOP;
  public static String VIDEO_LOOP_BATCH;
  public static String VOTE_DOMAINS;
  public static String VOTE_QUEUE;
  public static String WEEK;
  public static final String WX_APP_SECRET = "966af6e0773173139df6d6144482b8ec";
  public static final int cacheDrawableNum = 20;
  public static String change;
  public static int localVersion = 57;
  public static String localVersionName = "2.8.7";
  public static final int pageCount = 30;
  public static int serverVersion = 57;
  public static String serviceVersionName = "";
  
  static
  {
    IMG_DOMAINS = "http://pic.qiushibaike.com/";
    CONTENT_DOMAINS = "http://m2.qiushibaike.com/";
    VOTE_DOMAINS = "http://vote.qiushibaike.com/";
    PUSH_DOMAINS = "http://push.qiushibaike.com/push";
    PUSH_DOMAINS_TEST = "http://push.qiushibaike.com/push_test";
    APP_LOGS = "http://log.qiushibaike.com/applog";
    UPDATE_URL = "";
    INSP = "http://insp.qiushibaike.com";
    NEARBY = "http://nearby.qiushibaike.com";
    RELATIONSHIP = "http://rel.qiushibaike.com";
    OFFICIAL = "http://public.qiushibaike.com";
    OFFICIAL_INFO = OFFICIAL + "/public/%1$s/%2$s";
    OFFICIAL_SUBSCRIBE = OFFICIAL + "/subscribe";
    OFFICIAL_SUBSCRIBE_LIST = OFFICIAL + "/myPublics/%1$s";
    CONTENT_IMAGE_URL = IMG_DOMAINS + "system/pictures/%1$s/%2$s/%3$s/%4$s";
    ARATAR_URL = IMG_DOMAINS + "system/avtnew/%1$s/%2$s/%3$s/%4$s";
    IS_UNSUBSCRIBE_TA = CONTENT_DOMAINS + "sub/%1$s";
    UNSUBSCRIBE_TA = CONTENT_DOMAINS + "unsub";
    SUBSCRIBE_TA = CONTENT_DOMAINS + "resub";
    LOGIN = CONTENT_DOMAINS + "user/signin";
    THIRDPARTY_LOGIN = CONTENT_DOMAINS + "user/v2/signin";
    REGISTER = CONTENT_DOMAINS + "user/v2/signup";
    FILLINFO = CONTENT_DOMAINS + "user/v3/signup";
    BINDEMAIL = CONTENT_DOMAINS + "user/v3/signup/bindemail";
    UNBIND_THIRD_PARTY = CONTENT_DOMAINS + "user/v3/signup/unbind";
    VERIFY_EMAIL = CONTENT_DOMAINS + "user/v3/signup/verifyemail";
    MY_INFO = CONTENT_DOMAINS + "user/my/info";
    MYCONTENTS = CONTENT_DOMAINS + "user/my/articles";
    PARTICIPATE = CONTENT_DOMAINS + "user/my/participate";
    LIKE = CONTENT_DOMAINS + "user/my/like";
    COLLECT_LIST = CONTENT_DOMAINS + "collect/list";
    COLLECT = CONTENT_DOMAINS + "collect/%1$s";
    DELETE_COLLECT = CONTENT_DOMAINS + "collect/%1$s/del";
    SUGGEST = CONTENT_DOMAINS + "article/list/suggest";
    LATEST = CONTENT_DOMAINS + "article/list/latest";
    TEXT = CONTENT_DOMAINS + "article/list/text";
    IMAGES = CONTENT_DOMAINS + "article/list/images";
    HOT_IMAGES = CONTENT_DOMAINS + "article/list/imgrank";
    HISTORY = CONTENT_DOMAINS + "article/history";
    DAY = CONTENT_DOMAINS + "article/list/day";
    WEEK = CONTENT_DOMAINS + "article/list/week";
    MONTH = CONTENT_DOMAINS + "article/list/month";
    VIDEO = CONTENT_DOMAINS + "article/list/video";
    VIDEO_LOOP = CONTENT_DOMAINS + "article/%1$s/loop";
    VIDEO_LOOP_BATCH = CONTENT_DOMAINS + "loop_queue";
    APPINFO = CONTENT_DOMAINS + "appinfo";
    VOTE_QUEUE = VOTE_DOMAINS + "vote_queue";
    COMMENT = CONTENT_DOMAINS + "article/%1$s/comments";
    REPORT_COMMENT = CONTENT_DOMAINS + "comment/%1$s/report";
    REPORT_ARTICLE = CONTENT_DOMAINS + "article/%1$s/report";
    VERIFY = CONTENT_DOMAINS + "user/verify";
    FEEDBACK = CONTENT_DOMAINS + "feedback";
    UPDATE_AVATAR = CONTENT_DOMAINS + "user/my/avatar";
    UPDATE_USERINFO = CONTENT_DOMAINS + "user/my/edit";
    USERINFO = CONTENT_DOMAINS + "user/my/info";
    ARTICLE_CREATE = CONTENT_DOMAINS + "article/create";
    DELETE_CREATE = CONTENT_DOMAINS + "article/%1$s/del";
    COMMENT_CREATE = CONTENT_DOMAINS + "article/%1$s/comment/create";
    USER_AVAILABLE = CONTENT_DOMAINS + "user/available";
    CONFIG = CONTENT_DOMAINS + "config";
    ONES_ARTICLES = CONTENT_DOMAINS + "user/%s/articles";
    AUDIT = INSP + "/review?sid=%1$d";
    REPORT = INSP + "/report";
    MAINPAGE = CONTENT_DOMAINS + "mainpage/list";
    MAINPAGE_ACTORS = CONTENT_DOMAINS + "mainpage/actors?id=%s&page=%s";
    MAINPAGE_CHECK = CONTENT_DOMAINS + "mainpage/check";
    URL_USER_INFO = NEARBY + "/user/%s/detail";
    URL_CONFIG = NEARBY + "/user/config";
    URL_MOBILE_BRAND_LIST = NEARBY + "/user/magic_mobile";
    URL_SEARCH_QIUYOU = NEARBY + "/user/search";
    URL_FETCH = NEARBY + "/nearby/fetch";
    URL_CLEAR = NEARBY + "/nearby/clear_loc";
    URL_RANDOM_DOOR_UPDATE = NEARBY + "/nearby/data_update?ts=%s";
    URL_GET_TOKEN = NEARBY + "/big_cover/%s/uptoken";
    URL_QINIU_KEY = NEARBY + "/big_cover/%s";
    NOTIFY_SETTING_GET = "http://bitmap.qiushibaike.com/bitmap/%s/get";
    NOTIFY_SETTING_SET = "http://bitmap.qiushibaike.com/bitmap/set";
    TOPIC_CLICK_STATISTIC = CONTENT_DOMAINS + "topic/hit/%s";
    REL_NEW_FAN_COUNT = RELATIONSHIP + "/relationship/%s/new_fan_count";
    REL_NEW_FAN_LIST = RELATIONSHIP + "/relationship/%1$s/new_fan_list?page=%2$s";
    REL_MOVEOFF_BLACKLIST = RELATIONSHIP + "/relationship/%s/unblack";
    REL_UNFOLLOW = RELATIONSHIP + "/relationship/%s/unfollow";
    REL_GET_RELATIONSHIP = RELATIONSHIP + "/relationship/%1$s/get_status?uid=%2$s";
    REL_FOLLOW = RELATIONSHIP + "/relationship/%s/follow";
    REL_BLACK = RELATIONSHIP + "/relationship/%s/black";
    REL_GET_FRIENDS = RELATIONSHIP + "/relationship/%1$s/friend_list?page=%2$s";
    REL_GET_FOLLOWS = RELATIONSHIP + "/relationship/%1$s/follow_list?page=%2$s";
    REL_GET_FANS = RELATIONSHIP + "/relationship/%1$s/fan_list?page=%2$s";
    REL_GET_BLACKLIST = RELATIONSHIP + "/relationship/%1$s/black_list?page=%2$s";
  }
  
  public static void init()
  {
    CONTENT_IMAGE_URL = IMG_DOMAINS + "system/pictures/%1$s/%2$s/%3$s/%4$s";
    ARATAR_URL = IMG_DOMAINS + "system/avtnew/%1$s/%2$s/%3$s/%4$s";
    LOGIN = CONTENT_DOMAINS + "user/signin";
    THIRDPARTY_LOGIN = CONTENT_DOMAINS + "user/v2/signin";
    REGISTER = CONTENT_DOMAINS + "user/v2/signup";
    FILLINFO = CONTENT_DOMAINS + "user/v3/signup";
    BINDEMAIL = CONTENT_DOMAINS + "user/v3/signup/bindemail";
    VERIFY_EMAIL = CONTENT_DOMAINS + "user/v3/signup/verifyemail";
    MY_INFO = CONTENT_DOMAINS + "user/my/info";
    UNBIND_THIRD_PARTY = CONTENT_DOMAINS + "user/v3/signup/unbind";
    MYCONTENTS = CONTENT_DOMAINS + "user/my/articles";
    PARTICIPATE = CONTENT_DOMAINS + "user/my/participate";
    LIKE = CONTENT_DOMAINS + "user/my/like";
    COLLECT_LIST = CONTENT_DOMAINS + "collect/list";
    COLLECT = CONTENT_DOMAINS + "collect/%1$s";
    DELETE_COLLECT = CONTENT_DOMAINS + "collect/%1$s/del";
    SUGGEST = CONTENT_DOMAINS + "article/list/suggest";
    LATEST = CONTENT_DOMAINS + "article/list/latest";
    TEXT = CONTENT_DOMAINS + "article/list/text";
    IMAGES = CONTENT_DOMAINS + "article/list/images";
    HOT_IMAGES = CONTENT_DOMAINS + "article/list/imgrank";
    HISTORY = CONTENT_DOMAINS + "article/history";
    DAY = CONTENT_DOMAINS + "article/list/day";
    WEEK = CONTENT_DOMAINS + "article/list/week";
    MONTH = CONTENT_DOMAINS + "article/list/month";
    VIDEO = CONTENT_DOMAINS + "article/list/video";
    VIDEO_LOOP = CONTENT_DOMAINS + "article/%1$s/loop";
    APPINFO = CONTENT_DOMAINS + "appinfo";
    VOTE_QUEUE = VOTE_DOMAINS + "vote_queue";
    COMMENT = CONTENT_DOMAINS + "article/%1$s/comments";
    REPORT_COMMENT = CONTENT_DOMAINS + "comment/%1$s/report";
    REPORT_ARTICLE = CONTENT_DOMAINS + "article/%1$s/report";
    VERIFY = CONTENT_DOMAINS + "user/verify";
    FEEDBACK = CONTENT_DOMAINS + "feedback";
    UPDATE_AVATAR = CONTENT_DOMAINS + "user/my/avatar";
    UPDATE_USERINFO = CONTENT_DOMAINS + "user/my/edit";
    USERINFO = CONTENT_DOMAINS + "user/my/info";
    ARTICLE_CREATE = CONTENT_DOMAINS + "article/create";
    DELETE_CREATE = CONTENT_DOMAINS + "article/%1$s/del";
    COMMENT_CREATE = CONTENT_DOMAINS + "article/%1$s/comment/create";
    USER_AVAILABLE = CONTENT_DOMAINS + "user/available";
    CONFIG = CONTENT_DOMAINS + "config";
    ONES_ARTICLES = CONTENT_DOMAINS + "user/%s/articles";
    AUDIT = INSP + "/review?sid=%1$d";
    REPORT = INSP + "/report";
    URL_USER_INFO = NEARBY + "/user/%s/detail";
    URL_CONFIG = NEARBY + "/user/config";
    URL_RANDOM_DOOR_UPDATE = NEARBY + "/nearby/data_update?ts=%s";
    URL_FETCH = NEARBY + "/nearby/fetch";
    URL_CLEAR = NEARBY + "/nearby/clear_loc";
    NOTIFY_SETTING_GET = "http://bitmap.qiushibaike.com/bitmap/%s/get";
    NOTIFY_SETTING_SET = "http://bitmap.qiushibaike.com/bitmap/set";
    TOPIC_CLICK_STATISTIC = CONTENT_DOMAINS + "topic/hit/%s";
    REL_NEW_FAN_COUNT = RELATIONSHIP + "/relationship/%s/new_fan_count";
    REL_NEW_FAN_LIST = RELATIONSHIP + "/relationship/%1$s/new_fan_list?page=%2$s";
    REL_MOVEOFF_BLACKLIST = RELATIONSHIP + "/relationship/%s/unblack";
    REL_UNFOLLOW = RELATIONSHIP + "/relationship/%s/unfollow";
    REL_GET_RELATIONSHIP = RELATIONSHIP + "/relationship/%1$s/get_status?uid=%2$s";
    REL_FOLLOW = RELATIONSHIP + "/relationship/%s/follow";
    REL_BLACK = RELATIONSHIP + "/relationship/%s/black";
    REL_GET_FRIENDS = RELATIONSHIP + "/relationship/%1$s/friend_list?page=%2$s";
    REL_GET_FOLLOWS = RELATIONSHIP + "/relationship/%1$s/follow_list?page=%2$s";
    REL_GET_FANS = RELATIONSHIP + "/relationship/%1$s/fan_list?page=%2$s";
    REL_DELETE_NEW_FANS = RELATIONSHIP + "/relationship/%s/delete_fan";
    MAINPAGE = CONTENT_DOMAINS + "mainpage/list";
    URL_SEARCH_QIUYOU = NEARBY + "/user/search";
  }
}
